site_name: Project Documentation
site_url: https://ferencbon.github.io/randomaigenstuffs/

docs_dir: docs

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: Print Site
